// packages/file-uploader/src/angular/Action.ts
import {
  Directive,
  HostBinding,
  HostListener,
  inject,
  Input,
  booleanAttribute,
} from "@angular/core";
import { Root } from "./Root";
import { Item } from "./Items";
@Directive({ selector: "button[uploadAction]", standalone: true })
export class Action {
  @Input({ required: true }) uploadAction!:
    | "start"
    | "pause"
    | "resume"
    | "retry"
    | "cancel"
    | "reset"
    | "remove"
    | "forget";
  @Input() uploadItemId?: string;
  private root = inject(Root);
  private item = inject(Item, { optional: true });
  @Input({ alias: "disabled", transform: booleanAttribute }) nativeDisabled =
    false;
  @HostBinding("disabled") get disabled() {
    const state = this.root.controls();
    return this.nativeDisabled || state?.disabled || state?.readOnly || false;
  }
  @HostListener("click", ["$event"]) click(event: Event) {
    queueMicrotask(() => {
      if (event.defaultPrevented || this.disabled) return;
      const id = this.uploadItemId ?? this.item?.uploadItem;
      if (this.uploadAction === "start") this.root.store.start(id);
      else if (id) void this.root.store[this.uploadAction](id);
    });
  }
}

// packages/file-uploader/src/react/Action.tsx
import { forwardRef, useContext, type ButtonHTMLAttributes } from "react";
import type { UploaderStore } from "../core";
import {
  ItemContext,
  useUploaderControls,
  useUploaderContext,
} from "./context";
export type UploadAction =
  | "start"
  | "pause"
  | "resume"
  | "retry"
  | "cancel"
  | "reset"
  | "remove"
  | "forget";
export const Action = forwardRef<
  HTMLButtonElement,
  ButtonHTMLAttributes<HTMLButtonElement> & {
    action: UploadAction;
    itemId?: string;
  }
>(function Action(
  { action, itemId, onClick, disabled, type = "button", ...props },
  ref,
) {
  const inherited = useContext(ItemContext),
    { store } = useUploaderContext(),
    state = useUploaderControls(),
    id = itemId ?? inherited ?? undefined;
  return (
    <button
      {...props}
      ref={ref}
      type={type}
      disabled={
        disabled ||
        state.disabled ||
        state.readOnly ||
        (action !== "start" && !id)
      }
      data-action={action}
      onClick={(event) => {
        onClick?.(event);
        if (event.defaultPrevented) return;
        if (action === "start") store.start(id);
        else if (id) void (store[action] as UploaderStore["pause"])(id);
      }}
    />
  );
});
