// packages/file-uploader/src/react/Selection.tsx
import {
  forwardRef,
  useEffect,
  useRef,
  type InputHTMLAttributes,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
} from "react";
import { useUploaderControls, useUploaderContext } from "./context";
export const Input = forwardRef<
  HTMLInputElement,
  InputHTMLAttributes<HTMLInputElement>
>(function Input({ onChange, disabled, ...props }, forwarded) {
  const context = useUploaderContext(),
    state = useUploaderControls(),
    ref = useRef<HTMLInputElement | null>(null);
  useEffect(() => {
    const input = ref.current;
    if (!input) return;
    context.inputs.add(input);
    return () => {
      context.inputs.delete(input);
    };
  }, [context]);
  return (
    <input
      {...props}
      type="file"
      disabled={disabled || state.disabled || state.readOnly}
      ref={(node) => {
        ref.current = node;
        if (typeof forwarded === "function") forwarded(node);
        else if (forwarded) forwarded.current = node;
      }}
      onChange={(event) => {
        onChange?.(event);
        if (event.defaultPrevented) return;
        void context.store.add(Array.from(event.currentTarget.files ?? []));
        event.currentTarget.value = "";
      }}
    />
  );
});
export const Trigger = forwardRef<
  HTMLButtonElement,
  ButtonHTMLAttributes<HTMLButtonElement>
>(function Trigger({ onClick, disabled, type = "button", ...props }, ref) {
  const { inputs } = useUploaderContext(),
    state = useUploaderControls();
  return (
    <button
      {...props}
      type={type}
      ref={ref}
      disabled={disabled || state.disabled || state.readOnly}
      onClick={(event) => {
        onClick?.(event);
        if (!event.defaultPrevented)
          [...inputs].find((input) => !input.disabled)?.click();
      }}
    />
  );
});
export const Dropzone = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(function Dropzone(
  { onDrop, onDragOver, onDragLeave, onDragEnter, ...props },
  ref,
) {
  const context = useUploaderContext(),
    state = useUploaderControls();
  return (
    <div
      {...props}
      ref={ref}
      data-disabled={state.disabled || undefined}
      data-readonly={state.readOnly || undefined}
      aria-disabled={state.disabled || state.readOnly || undefined}
      onDragEnter={(event) => {
        onDragEnter?.(event);
        if (!event.defaultPrevented && !state.disabled && !state.readOnly)
          event.currentTarget.dataset.dragging = "true";
      }}
      onDragLeave={(event) => {
        onDragLeave?.(event);
        if (!event.currentTarget.contains(event.relatedTarget as Node | null))
          delete event.currentTarget.dataset.dragging;
      }}
      onDragOver={(event) => {
        onDragOver?.(event);
        if (!state.disabled && !state.readOnly && !event.defaultPrevented) {
          event.preventDefault();
          event.dataTransfer.dropEffect = "copy";
        }
      }}
      onDrop={(event) => {
        onDrop?.(event);
        delete event.currentTarget.dataset.dragging;
        if (event.defaultPrevented || state.disabled || state.readOnly) return;
        event.preventDefault();
        void context.store.add(Array.from(event.dataTransfer.files));
      }}
    />
  );
});

// packages/file-uploader/src/angular/Selection.ts
import {
  Directive,
  ElementRef,
  HostBinding,
  HostListener,
  inject,
  OnInit,
  OnDestroy,
  Input as AngularInput,
  booleanAttribute,
  Output,
  EventEmitter,
} from "@angular/core";
import { Root } from "./Root";
@Directive({ selector: "input[uploadInput]", standalone: true })
export class Input implements OnInit, OnDestroy {
  private root = inject(Root);
  private element =
    inject<ElementRef<HTMLInputElement>>(ElementRef).nativeElement;
  @HostBinding("type") type = "file";
  @AngularInput({ alias: "disabled", transform: booleanAttribute })
  nativeDisabled = false;
  @HostBinding("disabled") get disabled() {
    const state = this.root.controls();
    return this.nativeDisabled || state?.disabled || state?.readOnly || false;
  }
  ngOnInit() {
    this.root.inputs.add(this.element);
  }
  ngOnDestroy() {
    this.root.inputs.delete(this.element);
  }
  @HostListener("change", ["$event"]) changed(event: Event) {
    const files = Array.from(this.element.files ?? []);
    queueMicrotask(() => {
      if (event.defaultPrevented || this.disabled) return;
      void this.root.store.add(files);
      this.element.value = "";
    });
  }
}
@Directive({ selector: "button[uploadTrigger]", standalone: true })
export class Trigger {
  private root = inject(Root);
  @AngularInput({ alias: "disabled", transform: booleanAttribute })
  nativeDisabled = false;
  @HostBinding("disabled") get disabled() {
    const state = this.root.controls();
    return this.nativeDisabled || state?.disabled || state?.readOnly || false;
  }
  @HostListener("click", ["$event"]) clicked(event: Event) {
    queueMicrotask(() => {
      if (!event.defaultPrevented && !this.disabled)
        [...this.root.inputs].find((input) => !input.disabled)?.click();
    });
  }
}
@Directive({
  selector: "[uploadDropzone]",
  standalone: true,
  exportAs: "uploadDropzone",
})
export class Dropzone {
  private root = inject(Root);
  private element = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  @Output() uploadBeforeDrop = new EventEmitter<DragEvent>();
  private blocked() {
    const state = this.root.controls();
    return state?.disabled || state?.readOnly;
  }
  @HostBinding("attr.aria-disabled") get disabled() {
    return this.blocked() || null;
  }
  @HostBinding("attr.data-dragging") dragging: string | null = null;
  @HostListener("dragover", ["$event"]) over(event: DragEvent) {
    if (!event.defaultPrevented && !this.blocked()) event.preventDefault();
  }
  @HostListener("dragenter", ["$event"]) enter(event: DragEvent) {
    if (!event.defaultPrevented && !this.blocked()) this.dragging = "true";
  }
  @HostListener("dragleave", ["$event"]) leave(event: DragEvent) {
    if (!this.element.contains(event.relatedTarget as Node | null))
      this.dragging = null;
  }
  @HostListener("drop", ["$event"]) drop(event: DragEvent) {
    this.dragging = null;
    this.uploadBeforeDrop.emit(event);
    if (event.defaultPrevented || this.blocked()) return;
    event.preventDefault();
    void this.root.store.add(Array.from(event.dataTransfer?.files ?? []));
  }
}
